### ISSUE TITLE
Tests in travis fail for AlleleFractionInitializerUnitTest.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk-protected#239]
Locally testing does ok but when run in Travis you get an error consistently.

The stack trace reads:

<pre>
org.broadinstitute.hellbender.tools.exome.allelefraction.AlleleFractionInitializerUnitTest.testInitialize FAILED
    java.lang.AssertionError: expected [0.0] but found [-0.023368743794425884]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:496)
        at org.testng.Assert.assertEquals(Assert.java:209)
        at org.testng.Assert.assertEquals(Assert.java:222)
        at org.broadinstitute.hellbender.tools.exome.allelefraction.AlleleFractionInitializerUnitTest.testInitialize(AlleleFractionInitializerUnitTest.java:41)
</pre>

**Comment by vruano** [comment]
@davidbenjamin perhaps a hostname/architecture random seed? Native libraries involved? Non determinism caused by multi-core Spark?

**Comment by davidbenjamin** [comment]
@vruano I'll get to the bottom of this.

**Comment by davidbenjamin** [comment]
@vruano I forgot to seed a few random generators in one class.  This is fixed in PR #241, which is currently under review.

**Comment by davidbenjamin** [comment]
I snuck it into PR #202 actually in order to get it to pass.

**Comment by samuelklee** [comment]
Got another one in travis build for #351:

    Gradle suite > Gradle test > org.broadinstitute.hellbender.tools.exome.allelefraction.AlleleFractionInitializerUnitTest.testInitialize FAILED
    java.lang.AssertionError: expected [0.0] but found [0.02006594020751029]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:496)
        at org.testng.Assert.assertEquals(Assert.java:209)
        at org.testng.Assert.assertEquals(Assert.java:222)
        at org.broadinstitute.hellbender.tools.exome.allelefraction.AlleleFractionInitializerUnitTest.testInitialize(AlleleFractionInitializerUnitTest.java:34)

**Comment by samuelklee** [comment]
I think this was closed in #427.
