### ISSUE TITLE
CalculateCoverageComponentsIntegrationTest.testSimpleMatrix fails intermittently

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk-protected#242]
```
org.broadinstitute.hellbender.tools.exome.CalculateCoverageComponentsIntegrationTest.testSimpleMatrix FAILED
    java.lang.AssertionError: expected [4] but found [3]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:496)
        at org.testng.Assert.assertEquals(Assert.java:125)
        at org.testng.Assert.assertEquals(Assert.java:372)
        at org.testng.Assert.assertEquals(Assert.java:382)
        at org.broadinstitute.hellbender.utils.pca.PCAUnitTest.assertEquals(PCAUnitTest.java:201)
        at org.broadinstitute.hellbender.tools.exome.CalculateCoverageComponentsIntegrationTest.testSimpleMatrix(CalculateCoverageComponentsIntegrationTest.java:54)
```

This was seen during rebuilds of #192

**Comment by lbergelson** [comment]
@vruano I made a ticket for this just in case others run into it.  Feel free to close if you think it's not relevant.

**Comment by vruano** [comment]
Interestingly I cannot reproduce the error and master is currently passing tests.

**Comment by vruano** [comment]
I tried to disable Spark on that tool which is on by default but either-way it passes the tests.

**Comment by lbergelson** [comment]
Must be some race condition in the tests then?  Or maybe something platform specific to travis?

**Comment by vruano** [comment]
So what should I do?! I can disable spark in the test to avoid future recurrences yet that is sweeping it under the carpet.

**Comment by vruano** [comment]
Btw this seems to affect @davidbenjamin issue as well as it passes in master.

**Comment by vruano** [comment]
Will close and it should have been fixed. Please open if it reappears.
