### ISSUE TITLE
PCAUnitTest.testSparkSVDOnTestMatrix failing intermittently on travis.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#266]
Gradle suite > Gradle test > org.broadinstitute.hellbender.utils.pca.PCAUnitTest.testSparkSVDOnTestMatrix FAILED
    java.lang.AssertionError: expected [4] but found [3]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:496)
        at org.testng.Assert.assertEquals(Assert.java:125)
        at org.testng.Assert.assertEquals(Assert.java:372)
        at org.testng.Assert.assertEquals(Assert.java:382)
        at org.broadinstitute.hellbender.utils.pca.PCAUnitTest.assertEquals(PCAUnitTest.java:201)
        at org.broadinstitute.hellbender.utils.pca.PCAUnitTest.testSparkSVDOnTestMatrix(PCAUnitTest.java:138)

**Comment by vruano** [comment]
I deactivate the use of Spark for PCA a while ago. Is this still happening?

**Comment by samuelklee** [comment]
still happening, e.g., see @davidbenjamin's recent PRs #314 and #326.  seems to intermittently resolve after restarting travis build.

**Comment by vruano** [comment]
@samuelklee how you experience this bug recently?... is possibly eradicated.

**Comment by samuelklee** [comment]
i haven't...i guess we can close.
