### ISSUE TITLE
NPE when doing coverage collection in WGS

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#319]
This looks like an issue in the code of ``SparkGenomeReadCounts``

Got it when testing on large HCC1143T bam file on both cluster and standalone modes.

Failing at:  ``final int newEnd = Math.min(newStart + binsize - 1, sequenceDictionary.getSequence(contig).getSequenceLength());`` 

My money is that sometimes the sequence of the contig returns null and we are not checking for that.

```
16/01/22 22:42:20 ERROR Executor: Exception in task 28874.0 in stage 0.0 (TID 28874)
java.lang.NullPointerException
        at org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCounts.createKey(SparkGenomeReadCounts.java:148)
        at org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCounts.lambda$collectReads$bc56242$1(SparkGenomeReadCounts.java:99)
        at org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCounts$$Lambda$167/2095690993.call(Unknown Source)
        at org.apache.spark.api.java.JavaPairRDD$$anonfun$toScalaFunction$1.apply(JavaPairRDD.scala:1027)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
        at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:205)
        at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:88)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:744)
```

As an aside, I think the processing is faster when running on a local temp directory (as opposed to a shared filesystem location as the tmpdir).

**Comment by LeeTL1220** [comment]
I have a fix in the spark Jar branch for issue #317
