### ISSUE TITLE
AllelicCNV failing ungracefully on a TCGA LUAD sample.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#345]
my guess is some adjacent SNPs might be causing overlaps that HashedListTargetCollection complains about.  will investigate.

    13:08:20.108 INFO  AllelicCNV - Starting workflow for sample TCGA-44-2659-01A-01W-0928-08...
    13:08:20.108 INFO  AllelicCNV - Loading input files...
    13:08:22.617 INFO  AllelicCNV - Shutting down engine
    [February 1, 2016 1:08:22 PM EST] org.broadinstitute.hellbender.tools.exome.AllelicCNV done. Elapsed time: 0.15 minutes.
    Runtime.totalMemory()=168820736
    java.lang.IllegalArgumentException: input intervals contain at least two overlapping intervals: org.broadinstitute.hellbender.tools.exome.AllelicCount@caf41bc0 and org.broadinstitute.hellbender.tools.exome.AllelicCount@caf41bc0
            at org.broadinstitute.hellbender.tools.exome.HashedListTargetCollection.checkForOverlaps(HashedListTargetCollection.java:79)
            at org.broadinstitute.hellbender.tools.exome.HashedListTargetCollection.<init>(HashedListTargetCollection.java:63)
            at org.broadinstitute.hellbender.tools.exome.Genome.<init>(Genome.java:30)
            at org.broadinstitute.hellbender.tools.exome.Genome.<init>(Genome.java:41)
            at org.broadinstitute.hellbender.tools.exome.AllelicCNV.runPipeline(AllelicCNV.java:170)
            at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
            at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:98)
            at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:146)
            at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:165)
            at org.broadinstitute.hellbender.Main.instanceMain(Main.java:66)
            at org.broadinstitute.hellbender.Main.main(Main.java:81)

**Comment by samuelklee** [comment]
also note that the error message does not print the overlapping intervals correctly.

**Comment by samuelklee** [comment]
Hmm...looks like this might not actually be a bug and was perhaps instead caused by a corrupt GetHetCoverage output.  A chunk of chr22 was printed twice in the tumor pulldown (and appeared in the middle of chrX---maybe an I/O- or Queue-related issue?), which caused the overlapping intervals.  I could not reproduce the bug, so I will close this issue for now.
