### ISSUE TITLE
SparkSingularValueDecomposerUnitTest.testBasicFunction failing in master

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#415]
Gradle suite > Gradle test > org.broadinstitute.hellbender.utils.svd.SparkSingularValueDecomposerUnitTest.testBasicFunction FAILED
    java.lang.OutOfMemoryError: Java heap space
        at org.apache.commons.math3.linear.BlockRealMatrix.createBlocksLayout(BlockRealMatrix.java:270)
        at org.apache.commons.math3.linear.BlockRealMatrix.<init>(BlockRealMatrix.java:106)
        at org.apache.commons.math3.linear.MatrixUtils.createRealMatrix(MatrixUtils.java:81)
        at org.apache.commons.math3.linear.MatrixUtils.createRealIdentityMatrix(MatrixUtils.java:176)
        at org.apache.commons.math3.linear.QRDecomposition$Solver.getInverse(QRDecomposition.java:473)
        at org.broadinstitute.hellbender.utils.svd.SVDTestUtils.assertUnitaryMatrix(SVDTestUtils.java:23)
        at org.broadinstitute.hellbender.utils.svd.SVDTestUtils.assertSVD(SVDTestUtils.java:72)
        at org.broadinstitute.hellbender.utils.svd.SparkSingularValueDecomposerUnitTest.testBasicFunction(SparkSingularValueDecomposerUnitTest.java:31)

**Comment by vruano** [comment]
I guess the solution may consist in reduce the size of the problem to avoid the OoM error given that travis  VM resources are restricted.

**Comment by samuelklee** [comment]
@lbergelson can you give us a hand with some travis issues?

if increasing resources is not an option then we'll go with @vruano's suggestion.  @LeeTL1220

**Comment by lbergelson** [comment]
The test jvm size is set very low right now.  It can likely be safely increased.  Do you know how much heap space you need for this test?

Currently the following extremely conservative settings are set.  These were configured when you were running in a vm with 3gb of memory total and never relaxed when we moved to a large vm.  The current vm has 7.5 gb available. 
```
    // set heap size for the test JVM(s)
    minHeapSize = "1G"
    maxHeapSize = "1.5G"
    jvmArgs = ['-Xmx2G']
```
You could probably just remove the heap size arguments and set `jvmArgs = ['Xmx6G']`.  If that fixes the problem you're good.  If it doesn't you'll have to reduce the size of the test input.
