### ISSUE TITLE
PadTargets - blows up on "correct" parameters

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk-protected#468]
tag 39c988c2dc7f669306d246a2191d16af50496640

according to the doc, this commandline is correct:
```
./gatk-launch PadTargets -O a.bed
```

but it blows up right away
```
java.lang.IllegalArgumentException: unexpected null file reference
	at org.broadinstitute.hellbender.utils.Utils.nonNull(Utils.java:535)
	at org.broadinstitute.hellbender.utils.Utils.regularReadableUserFile(Utils.java:612)
	at org.broadinstitute.hellbender.tools.exome.TargetUtils.readTargetFile(TargetUtils.java:28)
	at org.broadinstitute.hellbender.tools.exome.PadTargets.doWork(PadTargets.java:49)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:102)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:155)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:174)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:67)
	at org.broadinstitute.hellbender.Main.main(Main.java:82)
```

**Comment by LeeTL1220** [comment]
@akiezun Here is the doc from the forum:

``java -jar gatk-protected.jar PadTargets --targets initial_target_file.bed --output initial_target_file.padded.bed --padding 250``

**Comment by akiezun** [comment]
'--help' is the main doc that people use

**Comment by LeeTL1220** [comment]
Fixed in my branch.

**Comment by LeeTL1220** [comment]
Parameter was accidentally listed as optional.
