### ISSUE TITLE
PadTargets - blows up on IAE rather than UserException

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk-protected#469]
tag 39c988c2dc7f669306d246a2191d16af50496640

```
/gatk-launch PadTargets -O a.bed -T /Users/akiezun/IdeaProjects/gatk-protected//src/test/resources/org/broadinstitute/hellbender/tools/exome/targets.bed --padding -1
```

```
java.lang.IllegalArgumentException: Padding must be >= 0
	at org.broadinstitute.hellbender.utils.param.ParamUtils.isPositiveOrZero(ParamUtils.java:147)
	at org.broadinstitute.hellbender.tools.exome.TargetPadder.padTargetsFromBEDFeatures(TargetPadder.java:28)
	at org.broadinstitute.hellbender.tools.exome.PadTargets.doWork(PadTargets.java:51)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:102)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:155)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:174)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:67)
	at org.broadinstitute.hellbender.Main.main(Main.java:82)
```

this should stop with a UserException and no stacktrace.

**Comment by LeeTL1220** [comment]
Changed existing unit test to look for ``UserException.BadInput`` instead of ``IllegalArgumentException``
