### ISSUE TITLE
AllelicCNV should throw a proper exception when the number of Hets is low

### ISSUE THREAD

**Issue by asmirnov239** [broadinstitute/gatk-protected#684]
When running the WGS ACNV workflow on the highly downsampled samples, and using GetBayesianHetCoverage, which returned fewer hets(only 7) than GetHetCoverage, the AllelicCNV produces the following: 

```
org.apache.commons.math3.exception.NotStrictlyPositiveException: 0 is smaller than, or equal to, the minimum (0)
at org.apache.commons.math3.linear.AbstractRealMatrix.<init>(AbstractRealMatrix.java:68)
at org.apache.commons.math3.linear.Array2DRowRealMatrix.<init>(Array2DRowRealMatrix.java:60)
at org.broadinstitute.hellbender.tools.exome.SNPSegmenter.writeSegmentFile(SNPSegmenter.java:54)
at org.broadinstitute.hellbender.tools.exome.AllelicCNV.calculateAndWriteSNPSegmentation(AllelicCNV.java:370)
at org.broadinstitute.hellbender.tools.exome.AllelicCNV.performSNPSegmentationStep(AllelicCNV.java:340)
at org.broadinstitute.hellbender.tools.exome.AllelicCNV.runPipeline(AllelicCNV.java:263)
at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:108)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:166)
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:185)
at org.broadinstitute.hellbender.Main.instanceMain(Main.java:76)
at org.broadinstitute.hellbender.Main.main(Main.java:92)
```

Can we give a better error message when this happens?

**Comment by asmirnov239** [comment]
@samuelklee Could you take a look at it after you come back? Thank you!

**Comment by samuelklee** [comment]
Looks like this happens when we try to create a 0x1 `Array2DRowRealMatrix`, which should only happen when there are no hets (i.e., when the `TargetCollection` `snps` passed to `writeSegmentFile` is empty).  We should definitely throw a better exception in this case, but I don't understand why there are no hets being passed (rather than 7)?
