### ISSUE TITLE
Invalid ylim value in PlotACNVResults.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk-protected#856]
Exception was thrown when trying to plot the results of PerformJointSegmentation (PR #753) from both a WES and a WGS sample.

    Error in plot.window(...) : need finite 'ylim' values
    Calls: source ... SetUpPlotPerSeg -> plot -> plot.default -> localWindow -> plot.window
    In addition: There were 50 or more warnings (use warnings() to see the first 50)

        at org.broadinstitute.hellbender.utils.R.RScriptExecutor.exec(RScriptExecutor.java:163)
        at org.broadinstitute.hellbender.utils.plotter.ACNVPlotter.writeSegmentedAlleleFractionPlotPerSeg(ACNVPlotter.java:59)
        at org.broadinstitute.hellbender.tools.exome.PlotACNVResults.doWork(PlotACNVResults.java:77)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:109)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:167)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:186)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:94)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:101)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:113)
        at org.broadinstitute.hellbender.Main.main(Main.java:147)

**Comment by samuelklee** [comment]
I think this may have been closed in #889.
