### ISSUE TITLE
Duplicate key error in HaplotypeCaller

### ISSUE THREAD

**Issue by virtuabhi** [broadinstitute/gatk-protected#861]
Hi

I am getting a "Duplicate key" error when running GATK4 HaplotypeCaller on a sample from NA12878. I have extracted a small BAM file which generates the same error in a minute.

On the same BAM file - UnifiedGenotyper and HaplotypeCaller (from GATK 3.6) run successfully.

I am using HaplotypeCaller from gatk-protected (commit id - b24fb75bf474d87f5e2259617fef268a145b28c6 September 2016) and gatk (commit id - d418b68ca6b2b5f1b0b29ba7ef20d45f347512e9) branches.

The exception is
```
 java.lang.IllegalStateException: Duplicate key [B@7dbb876
	at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
	at java.util.HashMap.merge(HashMap.java:1253)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.PairHMMLikelihoodCalculationEngine.buildGapContinuationPenalties(PairHMMLikelihoodCalculationEngine.java:304)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.PairHMMLikelihoodCalculationEngine.computeReadLikelihoods(PairHMMLikelihoodCalculationEngine.java:253)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.PairHMMLikelihoodCalculationEngine.computeReadLikelihoods(PairHMMLikelihoodCalculationEngine.java:184)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCallerEngine.callRegion(HaplotypeCallerEngine.java:529)
	at org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller.apply(HaplotypeCaller.java:212)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:241)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:214)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:518)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:108)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:166)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:185)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:76)
	at org.broadinstitute.hellbender.Main.main(Main.java:92)
```

The command is 
```
java -Xmx6g \
 -jar gatk-protected-all-0ea829d-SNAPSHOT-spark_standalone.jar \
 HaplotypeCaller \
 -R human_g1k_v37.fasta \
 -I file.bam \
 -O file.vcf
```

Currently, I have put the BAM file and index in this Dropbox folder - https://www.dropbox.com/sh/ojid7vmjx57vt51/AAD8_N2ay-aLMZbvt09M71o3a?dl=0 . If there is a preferred method to share files and extract relevant reads then let me know.

I hope that this BAM file could help in fixing a bug. If someone is familiar with this error and could post why this error might have occured then I can work on fixing the file too.

Thanks
Abhishek

**Comment by davidbenjamin** [comment]
@virtuabhi I am getting the same error.  Did you ever resolve your issue?

**Comment by virtuabhi** [comment]
Hi David

I did not resolve the issue. However to suppress the error, I changed the code in file `PairHMMLikelihoodCalculationEngine.java`. This file has a function named `computeReadLikelihoods` which calls another function `buildGapContinuationPenalties` with `processedReads` as input. If we first remove the duplicates from `processedReads` list and pass only the unique elements, then the error does not occur.

But I did not calculate the impact on final output after making this change.

```java
    private void computeReadLikelihoods(final LikelihoodMatrix<Haplotype> likelihoods) {
        // Modify the read qualities by applying the PCR error model and capping the minimum base,insertion,deletion qualities
        final List<GATKRead> processedReads = modifyReadQualities(likelihoods.reads());

        Set<GATKRead> uniqueSet = new LinkedHashSet<GATKRead>(processedReads);
        List<GATKRead> uniqueReads = new ArrayList<GATKRead>();
        uniqueReads.addAll(uniqueSet);

        // Passing uniqueReads instead of processedReads
        final Map<GATKRead, byte[]> gapContinuationPenalties = buildGapContinuationPenalties(uniqueReads, constantGCP);

        // Run the PairHMM to calculate the log10 likelihood of each (processed) reads' arising from each haplotype
        pairHMM.computeLog10Likelihoods(likelihoods, processedReads, gapContinuationPenalties);
        writeDebugLikelihoods(likelihoods);
    }
```

Thanks
Abhishek

**Comment by davidbenjamin** [comment]
Hi @virtuabhi,

It's very kind of you to reply to quickly to such an old ticket. Your fix makes sense because the duplicate key exception in the stack trace ultimately comes from repeated reads.  I looked into GATK 3 code and the reason the error doesn't happen there is that its`buildGapContinuationPenalties` looks like
```java
result = new HashMap<>();
for (read : reads) {
  result.put(read, something);
}
```
which doesn't throw an error because `put(read that's already in the hash map, something)` just replaces the old entry.  In GATK 4 we use Java 8 and the same method looks like
```java
result = reads.stream().collect(Collectors.toMap(read -> read, read -> something));
``
which *does* throw an error when there are duplicate reads.  Your solution achieves the same result as the GATK 3 code in a more explicit way.

Now it's an interesting question what we should do in GATK 4.  On the one hand, a valid bam file won't have the same read appear multiple times.  I ran the Picard tool ValidateSamFile on the bam that was causing me problems and it showed a bunch of problems with the bam.  On the other hand, bad bams come up from time to time and maybe it's worth getting results on them without reprocessing the whole pipeline starting from the fasta file to obtain a fully-compliant bam.

Thank you very much for sharing what you found.  It really helped clarify the issue for me.

Regards,
David
