### ISSUE TITLE
M2 WDL fails on SplitIntervals when scatter count = 1

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk-protected#908]
In stderr of the task:

```
Runtime.totalMemory()=1222115328
htsjdk.samtools.SAMException: Cannot write file because it is a directory: /cromwell-executions/Mutect2/796ecbec-1a78-499e-a616-cc6783c757f4/call-Mutect2/shard-0/Mutect2/1cafa37b-8402-4717-8c2f-142b9e87be2a/call-SplitIntervals/execution/interval-files
        at htsjdk.samtools.util.IOUtil.assertFileIsWritable(IOUtil.java:396)
        at org.broadinstitute.hellbender.tools.picard.interval.IntervalListTools.doWork(IntervalListTools.java:149)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:112)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
        at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgram.instanceMain(PicardCommandLineProgram.java:62)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:96)
        at org.broadinstitute.hellbender.Main.instanceMain(Main.java:103)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:116)
        at org.broadinstitute.hellbender.Main.main(Main.java:158)
ln: failed to access '*.interval_list': No such file or directory


```

**Comment by LeeTL1220** [comment]
Workaround is to set scatter count to a number greater than 1.

This happens because the tool will create a file when splitting an interval one way and creates a directory when splitting more than one way.
